### ISSUE TITLE
Monthly Charge Showing HTML

### ISSUE THREAD

**Issue by notserpmh** [poundifdef/VirginMobileMinutesChecker#17]
The "Monthly Charge" item in the app is now showing most of the HTML for the page instead of the correct monthly charge.  This is because VM changed the HTML of their page. 

Line 140 of WebsiteScraper.java:

`srch = "<h3>Monthly Charge</h3><p>";`

Should now be:

`srch = "<h3>Next Month's Charge</h3><p>";`

That should fix the bug I think.  I currently don't have a dev environment setup to test/build Android apps, but I will try to set one up in the next few days to test if I can.  I thought I would just post it as a bug since it might be a quick fix for someone who is already setup to work on the project.

Thanks for all your hard work on this project!   It is a big help!

**Comment by poundifdef** [comment]
Yep, just needed to make the change and push out the fix. Thanks for reporting this!

**Comment by notserpmh** [comment]
No problem.  Saw the update in the market today.  Thanks so much for your help and for your awesome program!
