### ISSUE TITLE
1.3 commit changed defaults in only 1 of 2 places

### ISSUE THREAD

**Issue by drfloob** [poundifdef/VirginMobileMinutesChecker#3]
in [your v1.3 commit](https://github.com/poundifdef/VirginMobileMinutesChecker/commit/115ffb16d051101ec886976f7862e5b11b190b7c), you changed the default `outgoingCallPrefTitle` to true, but the default in code is false (see MinutesService.java around line 57). So it wasn't actually on by default. I verified that just visiting the settings screen showed a checked box next to the option, which then was enough to make the pref stick as "true".

**Comment by poundifdef** [comment]
Okay - it looks like when I was mucking around in your updates, I didn't do a thorough job making sure all of my own changes were consistent! (note to self: programming is harder than it looks.) Thank you for pointing this out, will definitely fix.
